name: CI

on: #määrittelee missä tilanteessa actionit suoritetaan -> nyt aina kun tulee push tai pull
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs: #määritellään "työt" eli tehtäväsarja, nyt määritelty ainoastaa "build"
  build:
    runs-on: ubuntu-latest #GhitHub varaa työn askelia varten virtuaalikoneen - tässä määtirellään millainen OS käytössä

    steps: #yksittäine työ koostuu askeleista eli "steps"
      - uses: actions/checkout@v2 # suorittaa actionin checkout -> "checks-out your repository under $GITHUB_WORKSAPCE, so your workflow can access it"
      - name: Set up Python 3.6 # set-up asentaa halutun pythonin virtuaalikoneelle (löytyy marketplacesta, olisi hankalampi operaatio ilman)
        uses: actions/setup-python@v2
        with:
          python-version: 3.6
      - name: Install Poetry #suorittaa komentorivillä komennon, joka asentaa Poetryn
        run: pip install poetry
      - name: Install dependencies #asentaa kaikki projektin riippuvuudet
        run: poetry install
      - name: Run tests #kaikista tärkein ja suorittaa poetry:n avulla testit
        run: poetry run coverage run --branch -m pytest # ja kerää testikattavuuden
      - name: Coverage report
        run: poetry run coverage xml #muodostetaan XML-muotoinen raportti
      - name: Coverage report to Codecov
        run: bash <(curl -s https://codecov.io/bash) #lähetetään se Codecov:iin
